site_name: xt-training
nav:
  - Home: README.md
  - Getting started: getting-started.md
  - The basis for xt-training: basis.md
  - Source Code: https://github.com/XtractTech/xt-training
  - Python package index: https://pypi.org/project/xt-training/
  - Examples and Recipes:
    - Image classification: Image-Classification.ipynb
    - Audio data classification: Audio-Data-Classification.ipynb
theme: readthedocs

plugins:
  - mkdocs-jupyter:
      include_source: True

extra_css: [extra.css]
